# Generated by Django 5.0.6 on 2024-05-14 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Sexo',
        ),
    ]
