# Generated by Django 5.0.6 on 2024-05-14 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Estudios', '0002_delete_persona_delete_sexo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre del area')),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Maquina',
            fields=[
                ('id_maquina', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Máquina')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255, verbose_name='Tipo de actividad')),
            ],
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id_turno', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_turno', models.CharField(max_length=255, verbose_name='Tipo de Turno')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivoCompartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='archivos_compartidos/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id_estudio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField()),
                ('tiempo_inicio', models.DateTimeField(blank=True, null=True)),
                ('tiempo_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion', models.DurationField(blank=True, null=True)),
                ('cronometro', models.IntegerField(default=0)),
                ('pausado', models.BooleanField(default=False)),
                ('tiempo_pausa', models.DateTimeField(blank=True, null=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area', to='Estudios.area', verbose_name='area')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maquina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquina', to='Estudios.maquina', verbose_name='maquina')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Estudios.estudio')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('color', models.CharField(default='#34e610', max_length=7)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudios.estudio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estudios.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tiempo_vuelta', models.DurationField()),
                ('tiempo_total', models.DurationField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vueltas', to='Estudios.actividad')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vuelta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='Estudios.vuelta')),
            ],
        ),
    ]
