# Generated by Django 5.0.6 on 2024-05-15 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estudios', '0004_delete_comentario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turnos',
        ),
        migrations.AddField(
            model_name='area',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maquina',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='maquinas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipo',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to=settings.AUTH_USER_MODEL),
        ),
    ]
